variables:
  GIT_SUBMODULE_STRATEGY: recursive

image: ody55eus/emacs-straight

pages:
  script:
    - emacs --quick --script publish.el --funcall=jp/publish-html
  artifacts:
    paths:
      - public
  only:
    - master
