:PROPERTIES:
:ID:       bed2da3b-5356-4834-9d43-b27d52873e34
:END:
#+TITLE: Ody55eus - About Me

Dear visitor,

welcome to my odyssey through science. This little corner of the web lets you follow me on my way as I stumble across numerous phenomena in multidisciplinary fields.

This web-page is constantly growing and improving.

* About Me
My name is Jonathan Pieper, I am a researcher in physics, data science, and machine learning. I finished my master’s degree at Goethe University Frankfurt in 2021. I am currently searching for new projects to advance science.

I majored physics with focus on information technology. During my academic studies I focused on solid state physics to retrace how computers intrinsically operate.
During my bachelor and [[id:c3b47664-b69b-4eb2-a09f-66325d5566fe][master thesis]], I studied the magnetic nature of novel nanostructures and their intrinsic statistical behavior.
In this process, I focused on statistical data analysis, scrutinizing noisy signals in detail with fluctuation spectroscopy, observing the frequency space of fluctuations using Fourier transformation.

* Projects
To see all my Projects, take a look at the [[projects.org][Projects Overview]].
** Awesome Text Editors
During the time after I finished my masters degree, I explored some additional ways to auto-didactically educate myself. On this journey I rediscovered the amazing keyboard focused editors [[id:7bd0d14c-b748-4f05-8c70-36fbf0a94745][Emacs]] and [[id:55274963-7de7-4ddb-ba29-43b04adc1c44][Vim]]. Such tools adapt towards easy and quick use and help concentrate on the tasks at hand rather than how to interact with the computer.
** Zettelkasten
 The book [[id:f80807b8-91f4-4799-92a3-076d1c1a045a][How to take smart notes]] inspired me to overthink my (non-existent) note taking system. The Emacs package [[id:5064b908-04f6-4167-a66c-072073109ef1][Org Roam]], which just released the new major version 2.0 at that moment, is the tool of choice for me to implement the Zettelkasten system on my computer.
* This Site
This site is created using [[id:7bd0d14c-b748-4f05-8c70-36fbf0a94745][Emacs]] and [[id:afe3de83-e5b8-4f53-b457-987dd9bd579d][Org Mode]].
For more information, please consult the [[id:1e0af5aa-7042-47f2-abb0-01c55b13f25b][Readme.org]].
** License
All content on this page is licensed under [[http://creativecommons.org/licenses/by-sa/4.0/][CC BY-SA]]. You can use, copy and share all texts freely if you use a compatible license.
The source code creating this page is published on [[https://gitlab.com/ody55eus/ody55eus.gitlab.io][GitLab]] under the [[https://www.gnu.org/licenses/gpl-3.0.en.html][GNU GPL]] license. This license also grants everyone the invocable rights to use, modify and share the code under the given requirements.
