name: Publish to GitHub Pages

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install Emacs
        run: sudo apt install emacs-nox --yes

      - name: Clone dotfiles
        run: git clone https://gitlab.com/ody55eus/dotfiles.git

      - name: Build the site
        run: emacs --quick --script publish.el --funcall=jp/publish-html

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
